### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by SpaceboyRoss01** [sidorares/ntk#29]
```js
const FontManager = require("font-manager");
const ntk = require("ntk");
const x11 = require("x11");

function setFont(i,ctx) {
	var fnt = FontManager.getAvailableFontsSync()[i];
	var font = ctx.loadFont(fnt.path,fnt.weight,10,10);
	ctx.setFont(font);
	return ctx;
}

function draw(ctx,wnd) {
	setFont(0,ctx);
	ctx.fillStyle = "blue";
	ctx.fillRect(0,0,wnd.width,wnd.height);
	var txt = "Unfortunately, TGAC has stopped working!";
	ctx.fillText(txt,(wnd.width/2)-(ctx.measureText(txt).width/2),(wnd.height/2)-(ctx.measureText(txt).height/2));
}

ntk.createClient( (err, app) => {
	var window = app.createWindow({ width: 500, height: 300, title: "TGAC" });
	var ctx = window.getContext("2d");
	window.on("resize",(ev) => {
		draw(ctx,window);
	});
	window.map();
	draw(ctx,window);
});
```
This code results in this error:
```
/home/spaceboyross/Documents/TGAC/node_modules/ntk/lib/glyphset.js:13
    X.FreeGlyphSet(obj.id);
                      ^

TypeError: Cannot read property 'id' of undefined
    at EventEmitter.<anonymous> (/home/spaceboyross/Documents/TGAC/node_modules/ntk/lib/glyphset.js:13:23)
    at emitNone (events.js:86:13)
    at EventEmitter.emit (events.js:188:7)
    at callback (/home/spaceboyross/Documents/TGAC/node_modules/weak/lib/weak.js:108:11)
```

**Comment by sidorares** [comment]
thanks @SpaceboyRoss01 , I'll have a look later today when I'm at linux desktop

not sure exactly why obj can be undefined here https://github.com/sidorares/ntk/blob/e57066fe4679a6457e4cea39b3170299d6ce6a18/lib/glyphset.js#L12

you cat temporarily try to comment out `X.FreeGlyphSet(obj.id);` line that causes error

**Comment by SpaceboyRoss01** [comment]
I patched it myself by changing the code to
```js
var ref = weak(this,() => {
    X.FreeGlyphSet(this.id);
});
```

**Comment by sidorares** [comment]
Fixed by #40 (commit 08018d3). The native `weak` module is gone entirely; `lib/glyphset.js` now uses a `FinalizationRegistry` and registers `{ Render, X, id }` as the held value at construction time, so the finalizer never dereferences a collected object — the `Cannot read property 'id' of undefined` path no longer exists. Cleanup after the X connection closes is also guarded via `safeRelease` (d7b80ba), so finalizers can't crash on a dead connection either.
